/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/ganache/smb/shares": {
    /** List all SMB shares */
    get: operations["listSmbShares"];
    /** Create a new SMB share */
    post: operations["createSmbShare"];
  };
  "/ganache/storage/zfs": {
    /** List ZFS Pools */
    get: operations["listZfsPools"];
    /** Create a new ZFS Pool */
    post: operations["createZfsPool"];
  };
  "/ganache/storage/zfs/datasets": {
    /** List ZFS Datasets */
    get: operations["listZfsDatasets"];
  };
  "/nodes/localhost/status": {
    /** Get system status (CPU, RAM, Uptime) - PBS Compatible */
    get: operations["getNodeStatus"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    SmbShare: {
      /** @example financeiro */
      name?: string;
      /** @example /mnt/tank/financeiro */
      path?: string;
      /** @description Allow guest access */
      guest_ok?: boolean;
      /** @description Read-only share */
      read_only?: boolean;
      /** @description Share description */
      comment?: string;
    };
    SmbShareConfig: {
      /** @description Share name (alphanumeric, underscore, hyphen only) */
      name: string;
      /** @description ZFS dataset mountpoint */
      path: string;
      /**
       * @description Allow guest access
       * @default false
       */
      guest_ok?: boolean;
      /**
       * @description Enable Apple Time Machine support
       * @default false
       */
      timemachine?: boolean;
    };
    ZfsPool: {
      /** @example tank */
      name?: string;
      /**
       * @example ONLINE
       * @enum {string}
       */
      health?: "ONLINE" | "DEGRADED" | "FAULTED" | "OFFLINE" | "UNAVAIL";
      /**
       * @description Pool size in bytes
       * @example 1000000000000
       */
      size?: number;
      /**
       * @description Free space in bytes
       * @example 800000000000
       */
      free?: number;
      /**
       * @description Allocated space in bytes
       * @example 200000000000
       */
      allocated?: number;
      /**
       * @description Fragmentation percentage
       * @example 15.5
       */
      fragmentation?: number;
    };
    ZfsPoolConfig: {
      /** @description Pool name */
      name: string;
      /** @description List of block devices */
      devices: string[];
      /**
       * @description RAID level
       * @enum {string}
       */
      raid_level?: "mirror" | "raidz1" | "raidz2" | "raidz3";
    };
    ZfsDataset: {
      /** @example tank/financeiro */
      name?: string;
      /** @example tank */
      pool?: string;
      /** @example /mnt/tank/financeiro */
      mountpoint?: string;
      /** @description Used space in bytes */
      used?: number;
      /** @description Available space in bytes */
      available?: number;
      /** @example lz4 */
      compression?: string;
      /** @description Access time tracking */
      atime?: boolean;
    };
    NodeStatus: {
      /** @description System uptime in seconds */
      uptime?: number;
      /** @description CPU usage (0.0 to 1.0) */
      cpu?: number;
      memory?: {
        /** @description Total memory in bytes */
        total?: number;
        /** @description Used memory in bytes */
        used?: number;
        /** @description Available memory in bytes */
        available?: number;
      };
      /** @description Load average (1m, 5m, 15m) */
      load_average?: number[];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** List all SMB shares */
  listSmbShares: {
    responses: {
      /** @description List of shares */
      200: {
        content: {
          "application/json": components["schemas"]["SmbShare"][];
        };
      };
    };
  };
  /** Create a new SMB share */
  createSmbShare: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SmbShareConfig"];
      };
    };
    responses: {
      /** @description Share created successfully (Task ID returned) */
      200: {
        content: {
          "application/json": string;
        };
      };
    };
  };
  /** List ZFS Pools */
  listZfsPools: {
    responses: {
      /** @description Active ZFS pools */
      200: {
        content: {
          "application/json": components["schemas"]["ZfsPool"][];
        };
      };
    };
  };
  /** Create a new ZFS Pool */
  createZfsPool: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ZfsPoolConfig"];
      };
    };
    responses: {
      /** @description Pool created successfully */
      200: {
        content: {
          "application/json": string;
        };
      };
    };
  };
  /** List ZFS Datasets */
  listZfsDatasets: {
    parameters: {
      query?: {
        pool?: string;
      };
    };
    responses: {
      /** @description List of datasets */
      200: {
        content: {
          "application/json": components["schemas"]["ZfsDataset"][];
        };
      };
    };
  };
  /** Get system status (CPU, RAM, Uptime) - PBS Compatible */
  getNodeStatus: {
    responses: {
      /** @description Node status */
      200: {
        content: {
          "application/json": components["schemas"]["NodeStatus"];
        };
      };
    };
  };
}
