[package]
name = "ganache-core"
version = "0.1.0"
edition = "2021"

[dependencies]
ganache-api = { path = "../ganache-api" }
ganache-lib = { path = "../ganache-lib" }
axum = "0.8.1"
tokio = { version = "1.43.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
utoipa = { version = "5.4.0", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "9.0.0", features = ["axum"] }
anyhow = "1.0.100"
tower-http = { version = "0.6.8", features = ["cors"] }

[dev-dependencies]
tempfile = "3.23.0"
