// Story 5-4: Security Monitoring Endpoints

use ganache_api::models::security::{EventFilter, SecurityAlert, SecurityEvent, SecurityMetrics};
use ganache_lib::{SecurityEventService, SecurityMetricsService};

/// Get security events with filtering and pagination
///
/// # Purpose
/// Returns security events from the in-memory cache with optional filters
///
/// @ref Story-5.4 - Security events endpoint
#[utoipa::path(
    get,
    path = "/api/v1/security/events",
    params(
        ("event_type" = Option<String>, Query, description = "Filter by event type"),
        ("user" = Option<String>, Query, description = "Filter by username"),
        ("source_ip" = Option<String>, Query, description = "Filter by source IP"),
        ("severity" = Option<String>, Query, description = "Filter by severity level"),
        ("date_from" = Option<String>, Query, description = "Filter from date (ISO 8601)"),
        ("date_to" = Option<String>, Query, description = "Filter to date (ISO 8601)"),
        ("limit" = Option<u32>, Query, description = "Maximum results (default: 100, max: 1000)"),
        ("offset" = Option<u32>, Query, description = "Pagination offset")
    ),
    responses(
        (status = 200, description = "List of security events", body = Vec<SecurityEvent>),
        (status = 400, description = "Invalid filter parameters")
    )
)]
async fn get_security_events(
    _user: AuthenticatedUser,
    axum::extract::Query(params): axum::extract::Query<std::collections::HashMap<String, String>>,
) -> Result<Json<Vec<SecurityEvent>>, (StatusCode, String)> {
    // Parse query parameters into EventFilter
    let filter = EventFilter {
        event_type: None, // TODO: Parse from params
        user: params.get("user").cloned(),
        source_ip: params.get("source_ip").cloned(),
        severity: None, // TODO: Parse from params
        date_from: params.get("date_from").cloned(),
        date_to: params.get("date_to").cloned(),
        limit: params
            .get("limit")
            .and_then(|s| s.parse().ok())
            .unwrap_or(100)
            .min(1000),
        offset: params.get("offset").and_then(|s| s.parse().ok()).unwrap_or(0),
    };

    match SecurityEventService::get_events(&filter) {
        Ok(events) => Ok(Json(events)),
        Err(e) => Err((StatusCode::INTERNAL_SERVER_ERROR, e.to_string())),
    }
}

/// Get aggregated security metrics
///
/// # Purpose
/// Returns real-time security metrics including events/min, active users, suspicious IPs
///
/// @ref Story-5.4 - Security metrics endpoint
#[utoipa::path(
    get,
    path = "/api/v1/security/metrics",
    responses(
        (status = 200, description = "Security metrics", body = SecurityMetrics)
    )
)]
async fn get_security_metrics(
    _user: AuthenticatedUser,
) -> Result<Json<SecurityMetrics>, (StatusCode, String)> {
    match SecurityMetricsService::calculate_metrics() {
        Ok(metrics) => Ok(Json(metrics)),
        Err(e) => Err((StatusCode::INTERNAL_SERVER_ERROR, e.to_string())),
    }
}

/// Get active security alerts
///
/// # Purpose
/// Returns list of active security alerts generated by the system
///
/// @ref Story-5.4 - Security alerts endpoint
#[utoipa::path(
    get,
    path = "/api/v1/security/alerts",
    responses(
        (status = 200, description = "List of active security alerts", body = Vec<SecurityAlert>)
    )
)]
async fn get_security_alerts(
    _user: AuthenticatedUser,
) -> Result<Json<Vec<SecurityAlert>>, (StatusCode, String)> {
    match SecurityMetricsService::generate_alerts() {
        Ok(alerts) => Ok(Json(alerts)),
        Err(e) => Err((StatusCode::INTERNAL_SERVER_ERROR, e.to_string( ))),
    }
}
